### ISSUE TITLE
Subtitles Disappeared

### ISSUE THREAD

**Issue by Accomodare** [YePpHa/crunchyroll-html5#118]
My English subtitles have disappeared for One Piece, but that's it. I can turn on subtitles for the show in other available languages, and other shows have English subtitles, but for some reason they just vanished on One Piece. They were there previously and automatically up until this point and I have no clue what happened. What's worse is that I can't disable or uninstall the extension either because videos don't even load or play without the extension installed, and so I have to use a new browser if I want to watch my show.

PLEASE FIX THIS!!!

**Comment by YePpHa** [comment]
It's possible that #112 will fix your issue. I'm not able to test it right now, but I assume that One Piece is using hardsubs for some reason.

**Comment by mendhak** [comment]
Same - unable to see subtitles in several shows.

I also tried clicking the English US subtitle link so I get the `ssid` querystring parameter. 

Try these

with querystring:
http://www.crunchyroll.com/jojos-bizarre-adventure/episode-4-overdrive-652087?ssid=108503

without querystring:
http://www.crunchyroll.com/rezero-starting-life-in-another-world-/episode-11-rem-702421

**Comment by YePpHa** [comment]
Should be fixed in the latest version I just released: https://github.com/YePpHa/crunchyroll-html5/releases/tag/v0.14.0
