### ISSUE TITLE
Not Recording my Watch History Or Episode Progress

### ISSUE THREAD

**Issue by KeitaShido** [YePpHa/crunchyroll-html5#132]
1. The Extension is not keeping track of my watch history
2. It Does Not Auto-play The Next Episode.
3. No Longer Keeping Track Of where i left off in an episode.

**Comment by irgendwie** [comment]
Can reproduce this issue - the same happens for me.
Seems like Crunchyroll finally switched to tls encryption! :tada: 

![2018-10-03-110744_615x39](https://user-images.githubusercontent.com/8360698/46401197-95acfb00-c6fc-11e8-9f23-fb0903906248.png)

**Comment by YePpHa** [comment]
Omg, I would've never imagined that they would do that. I guess I need to go through the code and remove all checks and references to `http`.
