### ISSUE TITLE
[Request] Button for next episode

### ISSUE THREAD

**Issue by rma6** [YePpHa/crunchyroll-html5#139]
It would be nice if the player had a button to go to the next episode, so I don't have to watch the endings.

**Comment by rma6** [comment]
It wasn't activated indeed, I had some issues with Chrome, but now it's
working Just fine. Thanks.

Em dom, 21 de out de 2018 14:25, valdearg <notifications@github.com>
escreveu:

**Comment by basxto** [comment]
This player even has a shortcut for that https://github.com/YePpHa/crunchyroll-html5/wiki/Shortcuts
