### ISSUE TITLE
Disable Subtitles Feature ?

### ISSUE THREAD

**Issue by Shinji1988** [YePpHa/crunchyroll-html5#15]
is it possible to add a feature to disable subtitles ? 

On some anime's like the old "Naruto" episodes the subs are hard coded in the video so every time i watch an old anime i get additional subtitles for another language i don't want to see.

**Comment by YePpHa** [comment]
Found the issue and fixed it. You can find the fix in the latest version: https://github.com/YePpHa/crunchyroll-html5/releases/tag/v0.5.3
