### ISSUE TITLE
Not working on new Crunchyroll update

### ISSUE THREAD

**Issue by Shinobi17** [YePpHa/crunchyroll-html5#152]
The chrome extension no longer works on the latest crunchyroll update

**Comment by crackerbad** [comment]
same problem

**Comment by justsignedtopostthisokay** [comment]
Same problem here since yesterday. The curious thing is that the extension still works (for chrome and firefox), BUT ONLY while whatching MOB PSYCHO 100 show, I haven't found any other anime that keep the extension's player since though.

**Comment by justsignedtopostthisokay** [comment]
Just noticed that the extension also still works while watching the episodes directly from the MyAnimeList website (those from [this page](https://myanimelist.net/watch/episode)). Very curious, and also it's a good option while waiting for the fix.

**Comment by irgendwie** [comment]
The userscript version is still working for me (firefox with violentmonkey) - didn't try the extension version

**Comment by angelussoares** [comment]
Same thing here, it works only with Mob Psycho 100

**Comment by Peuuuur-Noel** [comment]
MediaID not retrieved properly from the URL and player failed to replace the official.
I've submit a PR with a fix https://github.com/YePpHa/crunchyroll-html5/pull/153

**Comment by YePpHa** [comment]
Thanks to @Peuuuur-Noel the issue has been found and resolved. I'm currently in the process of releasing a new version with a fix for this issue.

**Comment by YePpHa** [comment]
Just an update. I've not submitted the update to both Mozilla and Google. Mozilla should already list the new update. However, for Google there can go up to about 60 minutes (from when I posted this) before the update is available.

**Comment by Sqwalou** [comment]
It seems the fix broke it for me.
The extension was working fine until a few days ago but now it can't seem to load any video on chrome.
I just get a black screen with no progress bar and no UI whatsoever, and it just displays the Pause and Play icons when clicking in, but the video never starts.
