### ISSUE TITLE
Change subtitle language in code?

### ISSUE THREAD

**Issue by nitrog0d** [YePpHa/crunchyroll-html5#16]
I can compile it.

**Comment by YePpHa** [comment]
Sorry for the late reply.

You will need to edit [Player.tsx#L121](https://github.com/YePpHa/crunchyroll-html5/blob/master/src/app/media/player/Player.tsx#L121) and replace the part that picks the default subtitle.

The subtitle object has the interface that's defined at [crunchyroll-lib/src/models/ISubtitle.ts](https://github.com/YePpHa/crunchyroll-lib/blob/master/src/models/ISubtitle.ts). It doesn't contain any locale information as it's not provided by Crunchyroll. However, it should be possible to extract that information from the title of the subtitle.

Below I've posted an example of what metadata is given about the subtitles without needing to download and decode the subtitles.

| title | author |
| ---- | ------- |
[English (US)] English (US) | avex
[Español] Español | crunchyroll_la
[Español (España)] Español (España) | crunchyroll_es
[Français (France)] Français (France) | cr_fr
[Português (Brasil)] Português (Brasil) | cr_pt
[العربية] العربية | cr_ar
[Italiano] Italiano | cr_it
[Deutsch] Deutsch | cr_de
[Русский] Русский | cr_ru

If that information is not enough it's possible to download them (it will increase the load time of a video), you will be able to get the actual language code (`lang_code`):
- `<subtitle_script id="268891" title="English (US)" play_res_x="640" play_res_y="360" lang_code="enUS" lang_string="English (US)" created="2017-07-25 20:49:06" progress_string="100%" status_string="Approved" wrap_style="0">`
- `<subtitle_script id="268917" title="Español" play_res_x="640" play_res_y="360" lang_code="esLA" lang_string="Español" created="2017-07-25 21:34:03" progress_string="100%" status_string="Approved" wrap_style="0">`

**Comment by pandavova** [comment]
Thats to complex for me, because i dont know how to code.
So I need to wait :/
