### ISSUE TITLE
No longer able to download from addons.mozilla

### ISSUE THREAD

**Issue by Lucannus** [YePpHa/crunchyroll-html5#161]
My Firefox updated and booted all unsigned addons. Have have switched over to ESR to allow, but now am unable to re-add the extension from addons.mozilla

**Comment by irgendwie** [comment]
This is a "bug" in Firefox, not this addon:

> Late on Friday May 3rd, we became aware of an issue with Firefox that prevented existing and new add-ons from running or being installed. We are very sorry for the inconvenience caused to people who use Firefox.

https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/

**Comment by YePpHa** [comment]
Issue on the Firefox side. I will close this. If future issues occur. You can create a new issue.
