### ISSUE TITLE
ServiceWorker registration failed

### ISSUE THREAD

**Issue by chinmay1** [YePpHa/crunchyroll-html5#18]
I know this is related to content security policy but this breaks the add-on.

Also its crunchyroll's problem =(

DOMException
code: 18
columnNumber: 0
data: null
filename: "http://static.ak.crunchyroll.com/versioned_assets/js/view/add_service_worker.154180ed.js"
lineNumber: 1
message: "The operation is insecure."
name: "SecurityError"
result: 2152923154
stack: "@http://static.ak.crunchyroll.com/versioned_assets/js/view/add_service_worker.154180ed.js:1:72\n"
__proto__: DOMExceptionPrototype { name: Getter, message: Getter, INDEX_SIZE_ERR: 1, … }

**Comment by YePpHa** [comment]
I'm pretty sure that the attached log from the console is from one of Crunchyroll's workers and not the worker I create. However, I will take a look at this.
What browser are you using including the version? Also are you using the web extension or the userscript?

**Comment by chinmay1** [comment]
Userscript with Greasemonkey.
Firefox Quantum 58.0.2.

**Comment by chinmay1** [comment]
Well it seems to be working again.
Even though I still get the same error.
Sorry about this.
