### ISSUE TITLE
Video plays without subtitles

### ISSUE THREAD

**Issue by ampheul** [YePpHa/crunchyroll-html5#19]
Video plays, but does not show subtitles in either firefox or chrome. 

Platform Ubuntu 17.10
Using tampermonkey for userscripts.

**Comment by YePpHa** [comment]
@ampheul have you tried to click on any of the links marked in the image below?
![image](https://user-images.githubusercontent.com/2348303/37526089-d081c920-292e-11e8-8075-f1fc8eadd9cc.png)

**Comment by ampheul** [comment]
I did not notice that before. For some reason the video no longer plays and I am unable to test it. I will close this if I can get it to work as it may not be a bug.

**Comment by CaelTheColher** [comment]
I'm having the same issue. Most of the time the subtitles are working just fine, but some times it wont work no matter what i try.

**Comment by CaelTheColher** [comment]
It is inconsistent overall

**Comment by SwadicalRag** [comment]
I'm experiencing this issue too. Interestingly it works fine if I select Spanish subtitles, but English subtitles are not working. (I don't understand Spanish)

I tried investigating the issue, but have no idea where to begin. I can help you out with some debugging  if you give me some directions.

![screenshot with console open](https://i.imgur.com/3CFznI4.png)
(i obfuscated all tracking IDs)

**Comment by SwadicalRag** [comment]
I did some digging: the subtitles load fine and are passed onto your `LibAss` class fine, but the octopus webworker isn't calling `render` or `renderFrames` properly. I'm not sure if this is intended behaviour, but it seems like one of the causes of the problem.

**Comment by SwadicalRag** [comment]
The `default.ttf` font is supposedly not loading too. Is this intentional?
![image](https://user-images.githubusercontent.com/10724598/40644798-6cdff184-6363-11e8-86e8-6f0418d1fec9.png)

**Comment by YePpHa** [comment]
@SwadicalRag if `default.tff` fails to load it wont be able to render anything. I'm not sure why it fails. I will need to look into this a bit.

**Comment by SwadicalRag** [comment]
I did more digging, the font not loading properly is an issue exclusive to the userscript build. The fonts load fine as from the webextension.

However, I'm getting this error from the webextension instead now:
![image](https://user-images.githubusercontent.com/10724598/40692690-6503ebd4-63f2-11e8-8d26-60bdcf24f71c.png)

**Comment by SwadicalRag** [comment]
selecting a German subtitle works fine, however
![image](https://user-images.githubusercontent.com/10724598/40692808-fe6f58e4-63f2-11e8-960e-fab7bb90b55f.png)

I notice that different font weights are being used between these two cases. Is this perhaps related to the cause of the issue?

**Comment by YePpHa** [comment]
What are Crunchyroll doing with their subtitles if they set the scale to 0? If the scale is 0 it means that nothing can be displayed. It's like trying to display a 0p video.

I've made a PR (#61)

**Comment by SwadicalRag** [comment]
I guess their ASS renderer must be ignoring that parameter? Anyway, I'm glad I could help and get this resolved.

back to watching anime instead of studying for my vital signs assessment 😍😍
