### ISSUE TITLE
Broken with embedded IFrames since 8.0.0

### ISSUE THREAD

**Issue by Skycoder42** [YePpHa/crunchyroll-html5#23]
Before Version 8.0.0 eveything worked perfectly, but since the update I can't play videos in embedded iframes anymore. Opening the IFrame in a new tab or window however still works. I enabled error logging and was able to catch an error. The errormessage itself is:

```
Uncaught (in promise) SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
```

The stack trace chrome shows me is only: `content-script.js:22 (Anonyme Funktion)`

I am using the official chrome extension from the store. I am using Chromium Version 65.0.3325.181.

For reference: The page that has the embedded video: http://proxer.me/watch/18841/10/gersub?ssl=0

Chrome also show the whole script (in it's obfuscated form) and marked the last line red, indicating the error happend somewhere in the last part. I copied and attached the first part of all the lines, maybe it is useful for finding the error.

[extension-log.txt](https://github.com/YePpHa/crunchyroll-html5/files/1857578/extension-log.txt)

**Comment by Skycoder42** [comment]
Random guess from the release notes: You store the volume settings via the pages local storage?

**Comment by YePpHa** [comment]
@Skycoder42 you're very much correct. It seems like the access to localStorage on an embedded video causes the issue. I will make a patch for this.

**Comment by Skycoder42** [comment]
I think the problem is the iframe itself, when copying the iframe link from the HTML code and opening it in a new window it still works - but I'm no expert on the topic.

**Comment by YePpHa** [comment]
@Skycoder42 something is preventing access to the localStorage, but I think the fix is to use GM_setValue/GM_getValue for userscripts and other APIs for the Chrome extension and the Firefox extension

**Comment by YePpHa** [comment]
@Skycoder42 I've made a [new version](https://github.com/YePpHa/crunchyroll-html5/releases/tag/v0.8.1) with a fix for this issue. It can take up to an hour before it's on the [Chrome Web Store](https://chrome.google.com/webstore/detail/ihegfgnkffeibpmnajnoiemkcmlbmhmi).
