### ISSUE TITLE
Firefox extension is not signed

### ISSUE THREAD

**Issue by CaelTheColher** [YePpHa/crunchyroll-html5#25]
![image](https://user-images.githubusercontent.com/16297430/38168227-113a0460-351d-11e8-88ca-77d53d00c919.png)
https://developer.mozilla.org/en-US/Add-ons/Distribution

**Comment by YePpHa** [comment]
Done, I had to make make a file smaller before I was able to upload it. Now that's done, you can get it at https://github.com/YePpHa/crunchyroll-html5/releases/latest with the filename `crunchyroll_html5-0.9.1-an.fx.xpi`.
