### ISSUE TITLE
CR's Store problem

### ISSUE THREAD

**Issue by oscar-beltran** [YePpHa/crunchyroll-html5#46]
Hi, when I open the [store of Crunchyroll](http://www.crunchyroll.com/store) all the content is replaced by the message "Loading HTML5 player...", like the picture:

![cr](https://user-images.githubusercontent.com/3323932/40009303-3a517858-5767-11e8-98c6-a18286b656d9.jpg)
Script's version: 0.10.1
Browser: Firefox 60.0 on linux
Sorry for my bad English.

**Comment by YePpHa** [comment]
Yeah, that's not supposed to happen. I will make a fix for it.
