### ISSUE TITLE
Embedded player stuck on "Loading HTML5 player..."

### ISSUE THREAD

**Issue by Skycoder42** [YePpHa/crunchyroll-html5#47]
For an embedded iframe video, the player get's stuck at that point - However this time without any error messages (I checked the console and activated errors in the plugin settings -still nothing).

This time it does work when you simply copy the url from the iframe and open it as a normal tab in the browser, so it seems to be related to beeing embedded as iframe.

Reference video: https://proxer.me/watch/18121/1/gersub

**Comment by YePpHa** [comment]
Hmm. I just tested it and if I click on reload frame it will load properly. I am not quite certain why, but I would need to some more testing to figure it out.

![image](https://user-images.githubusercontent.com/2348303/40011204-5e4372f8-57a7-11e8-82a7-91c14fd7973c.png)

**Comment by YePpHa** [comment]
I believe it has something to do with the `readystatechange` event not being registered correctly. I have made a possible fix for it (#51), which seems to be working. Hopefully it will fix the issue completely, but I'm not 100% sure.
