### ISSUE TITLE
[Chrome] Video player not changing to html5

### ISSUE THREAD

**Issue by andresbiso** [YePpHa/crunchyroll-html5#54]
Hi, thanks for the amazing work on the player.
For some videos the player is not changing to html5.
I left here a link to the one example I've found: [http://www.crunchyroll.com/kill-la-kill/kill-la-kill-pv-2-645079](http://www.crunchyroll.com/kill-la-kill/kill-la-kill-pv-2-645079)

**Comment by andresbiso** [comment]
Ok. It seem that by reinstalling the extension the problem was solved. I'll be closing the issue. Thanks for the quick response.

**Comment by GabrielDuarteM** [comment]
I visited the link and it happened with me as well, but as @andresbiso said, reinstalling solved the issue, not sure why.
