### ISSUE TITLE
An embed URL with missing parameters should be handled more gracefully

### ISSUE THREAD

**Issue by DoomTay** [YePpHa/crunchyroll-html5#66]
[Example](https://www.animenewsnetwork.com/video/20599/). This plugin will just silently fail while the Flash player will load the video just fine.

It's likely because an error is thrown if certain parameters are not there

https://github.com/YePpHa/crunchyroll-html5/blob/c7db506ec0626a5214abba666b451c2bae07d4e0/src/app/player/AffiliatePlayer.ts#L29-L32

**Comment by YePpHa** [comment]
You're correct. It seems like it's missing `video_format` and `video_quality`. The logic might be that it will fallback to a default value for both.

I will work on getting this fixed.

**Comment by DoomTay** [comment]
The config URL defined on the page/iframe itself has a default for format

**Comment by YePpHa** [comment]
I found out that they just set `video_format` to `0` and don't pass the `video_quality`. So I just do the same.
