### ISSUE TITLE
Weird Flickering

### ISSUE THREAD

**Issue by RuneMasterGaming** [YePpHa/crunchyroll-html5#7]
While in full screen the rightmost column of pixels flicker white occasionally at seemingly random intervals.

**Comment by YePpHa** [comment]
What browser are you using and are you using the userscript or webextension?

**Comment by RuneMasterGaming** [comment]
Firefox 49 and Userscript.

**Comment by YePpHa** [comment]
I was not able to reproduce it with a simple test in Firefox 49 for about 5 minutes. I have not noticed this issue at all on either the newest version of Chrome or the newest version of Firefox.

Does this happen for all videos? Have you seen this issue somewhere else like YouTube? Does the flickering always occur at the same time in the video (you can verify by pausing when you see it and go back a couple of seconds and play it again)?

**Comment by RuneMasterGaming** [comment]
I updated to latest nightly and the flickering went away, seems like a bug on firefox's side.
