### ISSUE TITLE
Unable to change video quality

### ISSUE THREAD

**Issue by kyoumei** [YePpHa/crunchyroll-html5#90]
Crunchyroll had a new player update and have moved the quality options into the actual player itself. Now when I try to play a video using the extension, it defaults to the lowest quality.

Any suggestions on how to get around this? Much prefer to use this player as the videos load way faster.

**Comment by nike4613** [comment]
When did crunchyroll have a player update? I just loaded it up and saw
![this](https://user-images.githubusercontent.com/10411129/43596550-38abfa2e-9645-11e8-87a7-e48d2d90efd8.png)
What country are you in? What account type do you have?

For an immediate fix, just put `p<quality>=1` after either a `?` or `&` in the URL, and it should save it.

**Comment by norsehealer** [comment]
@nike4613 it's random invites from CR, but I've read it has problems like resuming pause and constant buffering but still playing the ep behind the buffering screen.

**Comment by kyoumei** [comment]
@nike4613 I'm in Australia and I'm on a Premium account, this is how the player appears on my screen
![image](https://user-images.githubusercontent.com/42029255/43640900-0059007e-9765-11e8-84ed-42792bf724e7.png)

**Comment by YePpHa** [comment]
@kyoumei I don't have access to the new HTML5 player. Would it be possible to send me a dump of the HTML from that page to me (email: jepperm@gmail.com)? I'm quite interested in what they send to their player and it might be possible for me to get the necessary information to recreate the old quality selector until a proper menu is added to the player.

**Comment by kyoumei** [comment]
@YePpHa I've sent through an email, hopefully that's what you needed?

**Comment by YePpHa** [comment]
@kyoumei just saw it, thank you. It seems like they did the smart thing and used the HLS quality level feature instead of their own quality selector. Before they also used HLS but they had a master file for each quality whereas now they have all qualities inside the single master file.

It's going to take a bit longer than I had anticipated as I thought they still used the "old" method, but all in all it's a good change.

**Comment by YePpHa** [comment]
Below here is the interesting part. I've redacted the URL's as they're still active as of me writing this. I'm not sure if the adaptive part is only for newer series/episodes or if they're for everything on Crunchyroll.

Interesting tidbits:
- In `streams` the URLs all link to adaptive streams with multiple quality levels.
- They also list the hardsub versions including the one without any subs on.
- They will probably fallback to the hardsub version if WebAssembly isn't supported on the browser or something (not quite certain).
- They're also using the exact same Subtitle engine as I am (https://github.com/Dador/JavascriptSubtitlesOctopus).
- The URLs in `subtitles` actually link to not encrypted ass subtitles. The ones I'm able to fetch are retrieved from `http://www.crunchyroll.com/xml/?req=RpcApiVideoPlayer_GetStandardConfig&...` and they're all encrypted.
- The player is actually inside an iframe and it's using https (https://static.crunchyroll.com/vilos/player.html#).

```
{
  "metadata": {
    "id": "G6QW47G26",
    "type": "anime",
    "channel_id": null,
    "title": "Pain",
    "description": "The Scouts take a stand against a new enemy, but it's not just Titans they'll be fighting anymore.",
    "episode_number": "39",
    "display_episode_number": "39",
    "duration": 1435000
  },
  "thumbnail": {
    "url": "https://img1.ak.crunchyroll.com/i/spire3-tmb/a2d6e8cf6353edad325dfd90d68076941532880909_fwide.jpg"
  },
  "streams": [
    {
      "format": "hls",
      "audio_lang": "jaJP",
      "hardsub_lang": "esLA",
      "url": "<REDACTED>",
      "resolution": "adaptive"
    },
    {
      "format": "hls",
      "audio_lang": "jaJP",
      "hardsub_lang": null,
      "url": "<REDACTED>",
      "resolution": "adaptive"
    },
    {
      "format": "hls",
      "audio_lang": "jaJP",
      "hardsub_lang": "ptBR",
      "url": "<REDACTED>",
      "resolution": "adaptive"
    },
    {
      "format": "hls",
      "audio_lang": "jaJP",
      "hardsub_lang": "enUS",
      "url": "<REDACTED>",
      "resolution": "adaptive"
    }
  ],
  "ad_breaks": [],
  "subtitles": [
    {
      "language": "enUS",
      "url": "<REDACTED>",
      "title": "English (US)",
      "format": "ass"
    },
    {
      "language": "esLA",
      "url": "<REDACTED>",
      "title": "Español",
      "format": "ass"
    },
    {
      "language": "ptBR",
      "url": "<REDACTED>",
      "title": "Português (Brasil)",
      "format": "ass"
    }
  ]
}
```

__master.m3u8__ (the master file of the HLS format)
```
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2494465,RESOLUTION=1280x720,FRAME-RATE=23.974,CODECS="avc1.640028,mp4a.40.2"
<REDACTED URL>
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2494465,RESOLUTION=1280x720,FRAME-RATE=23.974,CODECS="avc1.640028,mp4a.40.2"
<REDACTED URL>
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2494465,RESOLUTION=1280x720,FRAME-RATE=23.974,CODECS="avc1.640028,mp4a.40.2"
<REDACTED URL>
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5648878,RESOLUTION=1920x1080,FRAME-RATE=23.974,CODECS="avc1.640028,mp4a.40.2"
<REDACTED URL>
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5648878,RESOLUTION=1920x1080,FRAME-RATE=23.974,CODECS="avc1.640028,mp4a.40.2"
<REDACTED URL>
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5648878,RESOLUTION=1920x1080,FRAME-RATE=23.974,CODECS="avc1.640028,mp4a.40.2"
<REDACTED URL>
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1098261,RESOLUTION=848x480,FRAME-RATE=23.974,CODECS="avc1.4d401f,mp4a.40.2"
<REDACTED URL>
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1098261,RESOLUTION=848x480,FRAME-RATE=23.974,CODECS="avc1.4d401f,mp4a.40.2"
<REDACTED URL>
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1098261,RESOLUTION=848x480,FRAME-RATE=23.974,CODECS="avc1.4d401f,mp4a.40.2"
<REDACTED URL>
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=577921,RESOLUTION=640x360,FRAME-RATE=23.974,CODECS="avc1.4d401e,mp4a.40.2"
<REDACTED URL>
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=577921,RESOLUTION=640x360,FRAME-RATE=23.974,CODECS="avc1.4d401e,mp4a.40.2"
<REDACTED URL>
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=577921,RESOLUTION=640x360,FRAME-RATE=23.974,CODECS="avc1.4d401e,mp4a.40.2"
<REDACTED URL>
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=413119,RESOLUTION=428x240,FRAME-RATE=23.974,CODECS="avc1.42c015,mp4a.40.2"
<REDACTED URL>
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=413119,RESOLUTION=428x240,FRAME-RATE=23.974,CODECS="avc1.42c015,mp4a.40.2"
<REDACTED URL>
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=413119,RESOLUTION=428x240,FRAME-RATE=23.974,CODECS="avc1.42c015,mp4a.40.2"
<REDACTED URL>
```

**Comment by YePpHa** [comment]
@kyoumei I've implemented the quality selection feature for people who're using the beta player. The only thing to note is that I haven't actually tested if it works as I currently don't have access to it.

Please test if this version works with the beta player. I've attached the artifacts for the newest build: [artifacts.zip](https://github.com/YePpHa/crunchyroll-html5/files/2321911/artifacts.zip)
