### ISSUE TITLE
Use actual time parameter when changing quality

### ISSUE THREAD

**Issue by LonMcGregor** [YePpHa/crunchyroll-html5#98]
**Steps**
1. Play video
2. Leave running for a few seconds
3. Pause video
4. Note timestamp
5. Change quality

**Expected Behaviour**
Video starts playing at newly selected quality, and at the time the video was at before quality was changed

**Actual Behaviour**
Pressing the change quality button sets the time query parameter to 0 so the video starts from time 0

**Additional Info**
*Browser* Vivaldi 1.16.1259.3 (Official Build) (64-bit)
*Crunchroll Account* Premium Member
*Extension Version* 0.11.0

**Comment by YePpHa** [comment]
This will be fixed in an upcoming PR that will move the quality selector into the player.
